name: fischi
description: Control your addressable led stripe

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  uuid: ^2.0.4
  http: ^0.12.1
  flutter_colorpicker: ^0.3.4
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  hydrated_bloc: ^5.0.3
  path_provider: ^1.6.11
  equatable: ^1.2.2
  transparent_image: ^1.0.0
  url_launcher: ^5.5.0
  json_annotation: ^3.0.1
  sliding_up_panel: ^1.0.2

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
