name: fischi
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  uuid: ^2.0.4
  http: ^0.12.1
  flutter_colorpicker: ^0.3.4
  bloc: ^4.0.0
  flutter_bloc: ^4.0.1
  hydrated_bloc: ^4.1.1
  path_provider: ^1.6.11
  equatable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
